package com.udacity.jwdnd.course1.cloudstorage.services;

import com.udacity.jwdnd.course1.cloudstorage.entity.FileDataEntity;
import com.udacity.jwdnd.course1.cloudstorage.entity.FileInfoEntity;
import com.udacity.jwdnd.course1.cloudstorage.mapper.FileMapper;
import com.udacity.jwdnd.course1.cloudstorage.model.File;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import javax.sql.rowset.serial.SerialBlob;
import java.io.IOException;
import java.sql.Blob;
import java.sql.SQLException;
import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * File handler service.
 *
 * @// TODO : 10-Sep-23 receive files, store them, retrieve them by id, ensure their size isn't past limit
 */
@Service
public class FileService {

    private List<FileInfoEntity> fileList;
    private final FileMapper fileMapper;


    public FileService(FileMapper fileMapper) {
        this.fileMapper = fileMapper;
    }

    public File getFileById(int fileId) {
        // @// TODO optimization, this uses two queries
        //        file.setFileData(fileMapper.getFileData(fileId).getFileData());
        return fileMapper.getOneFileInfo(fileId);
    }


    public List<FileInfoEntity> getFileList(int userId){
        //if file list is empty (this means the server just started)
        // then just set a new one and return it.
        if (fileList == null || fileList.isEmpty()) {
            setFileList(userId);
            return fileList;
        }
        //if there is a file list already, ensure it is for the same user
        AtomicInteger uId = new AtomicInteger();
        this.fileList.stream().peek(f -> uId.set(f.getUserId()));
        if (uId.get() == userId) {
            return fileList;
        }
        else {
            setFileList(userId);
        }
        return fileList;
    }

    public void setFileList(int userId) {
        fileList = fileMapper.getAllFilesFromUserId(userId);
    }

    public void uploadFile(MultipartFile file, int userId) throws SQLException, IOException {
        //TODO Verify file name isn't already present, verify file size is within limit, throw an error if either fails
        //call file factory to get type File instead of multiPartFile.
        FileInfoEntity fileInfoHolder = getFileInfoFromMultipartFile(file,userId);
        FileDataEntity fileDataHolder = getFileDataFromMultipartFile(file,userId);
        //Insert the file into DB, the fileMapper insert will return the newly created fileId.
        int fileId = fileMapper.insert(fileInfoHolder);
        //Use fileId to upload the file separately,
        // this is done in a separate query in case we want to handle special logic for file uploading here.
        fileMapper.updateFileData(fileDataHolder.getFileData(),fileId);
    }

    public FileInfoEntity getFileInfoFromMultipartFile(MultipartFile file, int userId) throws IOException, SQLException {
        //create a file object, the first null is the fileId which will be generated by ORM later
        return new FileInfoEntity(null, file.getOriginalFilename(), file.getContentType(),file.getSize(),userId);
    }

    public FileDataEntity getFileDataFromMultipartFile(MultipartFile file, int userId) throws IOException, SQLException {
        return new FileDataEntity(new SerialBlob(file.getBytes()));
    }
}
